import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs';
const origin='http://127.0.0.1:18830',evidence={checks:[]};
async function post(path,input){const r=await fetch(origin+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});return {status:r.status,body:await r.json()};}
async function rpc(name,input){const r=await post('/api/trpc/'+name,{json:input});return {status:r.status,data:r.body.result?.data?.json,error:r.body.error?.json?.message};}
function prng(seed,length){let state=2166136261;for(let i=0;i<seed.length;i++){state^=seed.charCodeAt(i);state+=(state<<1)+(state<<4)+(state<<7)+(state<<8)+(state<<24);}state>>>=0;let out='';while(out.length<length){state^=state<<13;state^=state>>>17;state^=state<<5;out+=(state>>>0).toString(16).padStart(8,'0');}return out.substring(0,length);}
async function cap(purpose){const issued=await post('/api/auth/cap/'+purpose+'/challenge',{});assert.equal(issued.status,200);const {token,challenge}=issued.body;const solutions=Array.from({length:challenge.c},(_,i)=>{const salt=prng(token+(i+1),challenge.s),target=prng(token+(i+1)+'d',challenge.d);for(let n=0;n<2000000;n++)if(crypto.createHash('sha256').update(salt+n).digest('hex').startsWith(target))return n;throw Error('test challenge limit');});const redeemed=await post('/api/auth/cap/'+purpose+'/redeem',{token,solutions});assert.equal(redeemed.status,200);assert.equal(redeemed.body.success,true);assert.equal((await post('/api/auth/cap/'+purpose+'/redeem',{token,solutions})).status,400);evidence.checks.push(purpose+' challenge and redeem via real HTTP; repeated redeem denied');return redeemed.body.token;}
for(let i=0;i<3;i++)await rpc('auth.login',{username:'admin10@example.test',password:'wrong-password'});
assert.match((await rpc('auth.login',{username:'admin10@example.test',password:'ticket10-admin-password'})).error,/CAPTCHA_REQUIRED/);
const loginToken=await cap('login');assert.equal((await rpc('auth.login',{username:'admin10@example.test',password:'ticket10-admin-password',capToken:loginToken})).data.id,1);evidence.checks.push('password sign-in succeeds after real HTTP Cap verification');
const registerToken=await cap('register'),username='cap10-'+Date.now()+'@example.test';assert.ok((await rpc('auth.register',{username,password:'ticket10-cap-password',capToken:registerToken})).data.id);evidence.checks.push('registration succeeds after real HTTP Cap verification');
assert.match((await rpc('auth.register',{username:'replay10@example.test',password:'ticket10-cap-password',capToken:registerToken})).error,/CAPTCHA_INVALID/);evidence.checks.push('redeemed registration token cannot register a second account');
fs.writeFileSync('/private/tmp/forwardx-282-ticket10/http-cap-evidence.json',JSON.stringify(evidence,null,2)+'\n');console.log(evidence);
