import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const root=process.cwd(), dir='/private/tmp/forwardx-282-ticket10';
process.env.DATABASE_TYPE='sqlite';
process.env.DATABASE_CONFIG_PATH=path.join(dir,'database.json');
process.env.FORWARDX_LOG_DIR=path.join(dir,'logs');
process.env.FORWARDX_DEV_PANEL='0';
const secret=path.join(dir,'jwt.txt');if(!fs.existsSync(secret))fs.writeFileSync(secret,crypto.randomBytes(32).toString('hex'),{mode:0o600});process.env.JWT_SECRET=fs.readFileSync(secret,'utf8');
const require=createRequire(path.join(root,'package.json'));
const express=require('express'), cookieParser=require('cookie-parser');
const {createExpressMiddleware}=require('@trpc/server/adapters/express');
const {createServer}=await import(pathToFileURL(require.resolve('vite')).href);
const source=file=>import(pathToFileURL(path.join(root,file)).href);
const runtime=await source('server/dbRuntime.ts'),db=await source('server/db.ts');
const {ensureDatabaseSchema}=await source('server/dbSchema.ts');
const users=await source('server/repositories/userRepository.ts');
const {appRouter}=await source('server/routers.ts'),{createContext}=await source('server/_core/context.ts');
const {signGoogleProof,GOOGLE_RECENT_COOKIE}=await source('server/routers/google.ts');
const {issueLoginSession}=await source('server/routers/auth.ts');
const {authCapRouter}=await source('server/authCaptcha.ts');
const {registerGoogleAuthRoutes}=await source('server/googleAuthRoutes.ts');
const {registerDatabaseHealthRoutes}=await source('server/databaseHealthRoutes.ts');
const {registerLocaleHintRoute}=await source('server/localeHint.ts');
const {seamlessMigrationRouter}=await source('server/seamlessPanelMigration.ts');
await runtime.connectDatabase({type:'sqlite',sqlite:{path:path.join(dir,'panel.db')}});await ensureDatabaseSchema();
if(!(await db.getUserById(1))){
 const adminId=await users.createUser({username:'admin10@example.test',password:'ticket10-admin-password',name:'旧管理员 / unchanged',role:'admin'});assert.equal(adminId,1);
 const oldId=await users.createUser({username:'disabled10@example.test',password:'ticket10-disabled-password',name:'旧停用用户 / unchanged'});
 await runtime.executeRaw('UPDATE users SET "accountEnabled"=0,"twoFactorEnabled"=1,"twoFactorSecret"=? WHERE id=?',['GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ',oldId]);
 // Rebuild only the disposable database to represent a pre-Google users table.
 const [{sql:currentSql}]=await runtime.queryRaw("SELECT sql FROM sqlite_master WHERE type='table' AND name='users'");
 const oldSql=currentSql.replace('CREATE TABLE "users"','CREATE TABLE "users_legacy"').replace(', "googleSubject" TEXT','').replace(', "googleEmail" TEXT','').replace(', "googleLinkedAt" INTEGER','').replace(', UNIQUE ("googleSubject")','');
 const columns=(await runtime.queryRaw('PRAGMA table_info(users)')).filter(r=>!['googleSubject','googleEmail','googleLinkedAt'].includes(r.name)).map(r=>'"'+r.name+'"').join(',');
 await runtime.executeRaw('PRAGMA foreign_keys=OFF');
 await runtime.executeRaw(oldSql);
 await runtime.executeRaw('INSERT INTO users_legacy ('+columns+') SELECT '+columns+' FROM users');
 await runtime.executeRaw('DROP TABLE users');
 await runtime.executeRaw('ALTER TABLE users_legacy RENAME TO users');
 await runtime.executeRaw('PRAGMA foreign_keys=ON');
 const before=await runtime.queryRaw('PRAGMA table_info(users)');assert.ok(!before.some(r=>r.name==='googleSubject'));
 await ensureDatabaseSchema();await ensureDatabaseSchema();
 assert.ok(await users.verifyUserPassword(1,'ticket10-admin-password'));assert.ok(await users.verifyUserPassword(oldId,'ticket10-disabled-password'));
 const old=await users.getUserById(oldId);assert.equal(old.accountEnabled,false);assert.equal(old.twoFactorEnabled,true);assert.equal(old.twoFactorSecret,'GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ');assert.equal(old.googleSubject,null);
 fs.writeFileSync(path.join(dir,'upgrade-evidence.json'),JSON.stringify({oldColumnsAbsent:true,schemaRuns:2,oldPasswordsWork:true,disabledAccountPreserved:old.accountEnabled===false,twoFactorPreserved:old.twoFactorEnabled,googleSubject:old.googleSubject},null,2)+'\n');
 const {resolveGoogleAccount}=await source('server/googleAccounts.ts');
 const google=await resolveGoogleAccount({subject:'fixture-google-only-10',email:'google10@example.test',name:'Google测试用户 unchanged'});
 fs.writeFileSync(path.join(dir,'google-user-id.txt'),String(google.id));
 await db.setSettings({siteTitle:'sni-panel 10验收'});
}
const app=express();app.use(express.json({limit:'10mb'}));app.use(cookieParser());app.use(authCapRouter);registerGoogleAuthRoutes(app);registerDatabaseHealthRoutes(app);registerLocaleHintRoute(app);app.use(seamlessMigrationRouter);
app.get('/__ticket10/as-admin',async(req,res,next)=>{try{await issueLoginSession({req,res},await db.getUserById(1),'browser');res.redirect('/settings');}catch(e){next(e);}});
app.get('/__ticket10/as-google',async(req,res,next)=>{try{const user=await db.getUserById(Number(fs.readFileSync(path.join(dir,'google-user-id.txt'),'utf8')));await issueLoginSession({req,res},user,'browser');res.cookie(GOOGLE_RECENT_COOKIE,signGoogleProof({purpose:'recent',userId:user.id,subject:user.googleSubject}),{httpOnly:true,sameSite:'lax',maxAge:300000});res.redirect('/profile');}catch(e){next(e);}});
app.get('/__ticket10/logout',async(req,res)=>{res.clearCookie('app_session_id');res.clearCookie('forwardx_session');res.redirect('/login');});
const sanitize=value=>Array.isArray(value)?value.map(sanitize):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([k,v])=>[/password|secret|token|code|state|cookie/i.test(k)?k:k,/password|secret|token|code|state|cookie/i.test(k)?'[redacted]':sanitize(v)])):value;
app.use('/api/trpc',(req,res,next)=>{fs.appendFileSync(path.join(dir,'requests.jsonl'),JSON.stringify({at:new Date().toISOString(),path:req.path,body:sanitize(req.body)})+'\n');next();});
app.use('/api/trpc',createExpressMiddleware({router:appRouter,createContext}));
const vite=await createServer({configFile:path.join(root,'vite.config.ts'),root,server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);
const server=app.listen(18830,'127.0.0.1',()=>console.log('Ticket10 ready http://127.0.0.1:18830/login'));
let closing=false;const stop=async()=>{if(closing)return;closing=true;server.closeAllConnections();await new Promise(r=>server.close(r));await vite.close();await runtime.closeDatabase();process.exit(0);};process.on('SIGINT',stop);process.on('SIGTERM',stop);
