import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
const root=process.cwd(),dir='/private/tmp/forwardx-282-ticket11';process.env.DATABASE_TYPE='sqlite';process.env.DATABASE_CONFIG_PATH=path.join(dir,'business-config.json');process.env.FORWARDX_LOG_DIR=path.join(dir,'business-logs');process.env.FORWARDX_SEAMLESS_MIGRATION_STATE_PATH=path.join(dir,'business-migration.json');process.env.TELEGRAM_BOT_TOKEN='';process.env.DISCORD_BOT_TOKEN='';process.env.JWT_SECRET='business-test-secret-32-characters';
const source=p=>import(pathToFileURL(path.join(root,p)).href),runtime=await source('server/dbRuntime.ts'),db=await source('server/db.ts');const {ensureDatabaseSchema}=await source('server/dbSchema.ts');
const {notifyForwardRuleError,notifyForwardRuleOccupancy}=await source('server/forwardRuleErrorNotifier.ts');const {notifyForwardGroupSwitch}=await source('server/forwardGroupSwitchNotifier.ts');const host=await source('server/hostStatusNotifier.ts');const {announcementsRouter}=await source('server/routers/announcements.ts');const {notificationRecipients}=await source('server/notifications.ts');
await runtime.connectDatabase({type:'sqlite',sqlite:{path:path.join(dir,'business3.db')}});await ensureDatabaseSchema();
for(const [id,role] of [[1,'admin'],[2,'user'],[3,'admin']]){
 assert.equal(await db.createUser({username:'business-'+id,password:'test-only-password',name:'Business '+id,role}),id);
 await runtime.executeRaw('UPDATE users SET "telegramId"=?,"discordId"=?,"telegramAnnouncementSubscribed"=1,"discordAnnouncementSubscribed"=1,"accountEnabled"=? WHERE id=?',[String(1000+id),String(123456789012345670n+BigInt(id)),id===3?0:1,id]);
}
await db.setSettings({telegramBotEnabled:'true',telegramBotToken:'tg-test-token',discordBotEnabled:'true',discordBotToken:'dc-test-token',telegramHostStatusNotify:'true',discordHostStatusNotify:'true'});
const receipts=[],channels=new Map(),evidence={checks:[]};
globalThis.fetch=async(url,options)=>{const u=new URL(String(url)),body=JSON.parse(String(options?.body||'{}'));if(u.hostname==='api.telegram.org'){receipts.push({provider:'telegram',recipient:body.chat_id,text:body.text});return Response.json({ok:true,result:{message_id:1}});}assert.equal(u.hostname,'discord.com');if(u.pathname.endsWith('/users/@me/channels')){const channel=String(BigInt(body.recipient_id)+100n);channels.set(channel,body.recipient_id);return Response.json({id:channel});}const channel=u.pathname.split('/')[4];receipts.push({provider:'discord',recipient:channels.get(channel),text:body.content});return Response.json({id:'345678901234567890'});};
const caller=announcementsRouter.createCaller({user:await db.getUserById(1),req:{headers:{}},res:{},authSession:null,authFailureReason:null});
function ok(name){evidence.checks.push({name,passed:true});console.log('PASS '+name);}
try{
 for(const [index,provider] of ['telegram','discord'].entries()){
  await db.setSetting('notificationChannel',provider);const adminId=provider==='telegram'?'1001':'123456789012345671',userId=provider==='telegram'?'1002':'123456789012345672';
  assert.deepEqual((await notificationRecipients('admin')).map(u=>u.id),[1]);assert.deepEqual((await notificationRecipients('announcement')).map(u=>u.id),[1,2]);ok(provider+' recipients exclude disabled administrators and preserve subscriber permissions');
  const start=receipts.length,rule={id:100+index,name:'notify rule <unchanged>',hostId:500+index,sourcePort:18000,targetIp:'192.0.2.3',targetPort:443,forwardType:'gost',protocol:'tcp',telegramErrorNotifyEnabled:true};
  await notifyForwardRuleError({rule,message:'target offline'});await notifyForwardRuleOccupancy({rule,message:'local listener 18000',recovered:false});await notifyForwardRuleOccupancy({rule,recovered:true});await notifyForwardGroupSwitch({groupId:600+index,groupName:'notify group',groupMode:'failover',reason:'entry unavailable',fromValue:'192.0.2.1',toValue:'192.0.2.2'});
  const hostId=await db.createHost({name:'notify-host-'+provider,userId:1,agentToken:'test-host-'+provider,ip:'192.0.2.1'});await host.primeHostStatusNotifier();await host.notifyHostOnlineIfNeeded({...await db.getHostById(hostId),isOnline:true,lastHeartbeat:new Date()});await runtime.executeRaw('UPDATE hosts SET "isOnline"=1,"lastHeartbeat"=? WHERE id=?',[Math.floor((Date.now()-3600000)/1000),hostId]);assert.equal(await host.sweepOfflineHostsAndNotify(),1);
  const privileged=receipts.slice(start);assert.equal(privileged.length,6);assert.ok(privileged.every(r=>r.provider===provider&&String(r.recipient)===adminId));for(const title of ['转发规则异常','端口占用警告','端口占用解除','转发组自动切换','主机上线','主机离线'])assert.ok(privileged.some(r=>r.text.includes(title)),title);ok(provider+' six real notification entry points send only to the selected-channel administrator');
  const announcement=await caller.create({title:'notify announcement '+provider,content:'<p>test announcement</p>',type:'normal',telegramPush:true});assert.deepEqual(announcement.telegramPush,{requested:true,sent:2,failed:0,total:2});const published=receipts.slice(start+6);assert.deepEqual(published.map(r=>String(r.recipient)).sort(),[adminId,userId].sort());ok(provider+' public announcement create delivers only to subscribed enabled users');
 }
 fs.writeFileSync(dir+'/business-evidence.json',JSON.stringify(evidence,null,2)+'\n');fs.writeFileSync(dir+'/business-receipts.json',JSON.stringify(receipts,null,2)+'\n');
}finally{await new Promise(r=>setImmediate(r));await runtime.closeDatabase();}
