import assert from 'node:assert/strict';import fs from 'node:fs';
const dir='/private/tmp/forwardx-282-ticket11',base='http://127.0.0.1:18831';const evidence={checks:[]};
function capture(jar,res){for(const cookie of res.headers.getSetCookie()){const pair=cookie.split(';',1)[0],at=pair.indexOf('=');const name=pair.slice(0,at),value=decodeURIComponent(pair.slice(at+1));if(value)jar.set(name,value);else jar.delete(name);}}
async function request(path,jar,init={}){const res=await fetch(base+path,{...init,redirect:'manual',headers:{...init.headers,Origin:base,Cookie:[...jar].map(([k,v])=>k+'='+encodeURIComponent(v)).join(';')}});capture(jar,res);return res;}
async function rpc(name,jar,input,query=false){const res=await request('/api/trpc/'+name+(query&&input!==undefined?'?input='+encodeURIComponent(JSON.stringify({json:input})):''),jar,query?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({json:input??null})});const body=await res.json();return {status:res.status,data:body.result?.data?.json,error:body.error?.json?.message,code:body.error?.json?.data?.code};}
const state=async()=> (await fetch(base+'/__ticket11/state')).json();
async function message(provider,text,actor){await fetch(base+'/__ticket11/message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,text,actor})});}
async function until(fn,timeout=40000){const deadline=Date.now()+timeout;while(Date.now()<deadline){const result=await fn();if(result)return result;await new Promise(r=>setTimeout(r,50));}throw new Error('Expected business result did not arrive');}
function ok(name){evidence.checks.push({name,passed:true});fs.writeFileSync(dir+'/http-evidence.json',JSON.stringify(evidence,null,2)+'\n');console.log('PASS '+name);}
const admin=new Map(),user=new Map(),anon=new Map();await request('/__ticket11/as-admin',admin);await request('/__ticket11/as-user',user);
const settings=(await rpc('system.getSettings',admin,undefined,true)).data;assert.equal(settings.notificationChannel,'discord');assert.equal(settings.telegram.configured,true);assert.equal(settings.discord.configured,true);assert.ok(!JSON.stringify(settings).includes('ticket11-dc-test-token'));assert.ok(!JSON.stringify(settings).includes('ticket11-tg-test-token'));ok('admin settings return masked credentials and preserve both providers');
assert.equal((await rpc('discord.testSend',user)).code,'FORBIDDEN');ok('ordinary user cannot test-send or configure admin notification settings');
if((await rpc('discord.status',user,undefined,true)).data.bound)await rpc('discord.unbind',user);
const bind=await rpc('discord.createBindCode',user);assert.ok(bind.data.code);await fetch(base+'/__ticket11/message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:'discord',text:'/bind '+bind.data.code,actor:'123456789012345679',type:'group'})});assert.equal((await state()).users[1].discordId,null);ok('public Discord channel cannot consume a bind code');
await message('discord','/bind '+bind.data.code,'123456789012345679');await until(async()=> (await state()).users[1].discordId);assert.equal((await state()).users[1].telegramId,'1002');ok('ordinary user binding through Gateway preserves the old Telegram identity');
await rpc('discord.subscribe',user,{enabled:true});assert.equal((await state()).users[1].discordAnnouncementSubscribed,true);ok('Discord subscription is stored independently');
for(const command of ['/menu','/usage','/rules','/users'])await message('discord',command,'123456789012345679');
await until(async()=>(()=>{try{return JSON.parse(fs.readFileSync(dir+'/platform.json')).some(r=>r.provider==='discord'&&r.body?.content?.includes('/usage - 查询我的用量'));}catch{return false;}})());ok('ordinary bot queries work while admin enumeration is rejected');
await message('discord','/login','123456789012345679');let code=await until(async()=> (await state()).users[1].discordLoginCode);
const loginJar=new Map(),login=await rpc('discord.login',loginJar,{code});assert.equal(login.data.id,2);assert.equal(login.data.role,'user');assert.equal('discordLoginCode' in login.data,false);assert.equal((await rpc('auth.me',loginJar,undefined,true)).data.id,2);assert.match((await rpc('discord.login',new Map(),{code})).error,/无效/);ok('Discord login creates a usable ordinary session and refuses the repeated code');
await request('/__ticket11/as-user',user);await rpc('discord.unbind',user);let current=await state();assert.equal(current.users[1].discordId,null);assert.equal(current.users[1].discordAnnouncementSubscribed,false);assert.equal(current.users[1].telegramId,'1002');ok('Discord unbind clears its subscription and keeps Telegram');
assert.equal((await rpc('system.updateSettings',admin,{notificationChannel:'telegram'})).error,undefined);current=await state();assert.equal(current.users[0].discordId,'123456789012345678');assert.equal(current.users[0].telegramId,'1001');assert.equal(current.users[0].discordAnnouncementSubscribed,true);ok('switching back to Telegram preserves Discord binding and subscription');
await message('telegram','/login','1002');code=await until(async()=> (await state()).users[1].telegramLoginCode);
const tgJar=new Map(),tgLogin=await rpc('telegram.login',tgJar,{code});assert.equal(tgLogin.data.id,2);assert.equal((await rpc('auth.me',tgJar,undefined,true)).data.id,2);assert.match((await rpc('telegram.login',new Map(),{code})).error,/无效/);ok('Telegram login through actual polling creates a session and is single-use');
await request('/__ticket11/as-user',user);await rpc('auth.updateProfile',user,{telegramAnnouncementSubscribed:false});assert.equal((await state()).users[1].telegramAnnouncementSubscribed,false);ok('Telegram announcement preference remains writable through the public account API');
await rpc('telegram.unbind',user);assert.equal((await state()).users[1].telegramId,null);const tgBind=await rpc('telegram.createBindCode',user);await message('telegram','/bind '+tgBind.data.code,'1002');await until(async()=> (await state()).users[1].telegramId);assert.equal((await state()).users[1].telegramBindCode,null);ok('Telegram unbind and new binding work through real polling and public account APIs');
await rpc('system.updateSettings',admin,{notificationChannel:'discord'});const final=(await rpc('system.getSettings',admin,undefined,true)).data;assert.equal(final.telegram.configured,true);assert.equal(final.discord.configured,true);assert.equal((await state()).users[0].telegramId,'1001');ok('final Discord selection keeps both saved configurations and admin bindings');
